version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t ./src

  pre_build:
    commands:
      - echo "Zipping the code..."
      - cd src
      - zip -r create-data.zip .

  build:
    commands:
      - echo "Uploading the code to Lambda function..."
      - aws lambda update-function-code --function-name create-data --zip-file fileb://create-data.zip

artifacts:
  files:
    - src/create-data.zip